import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import "../../legal.css";

export default function AirStreamPrivacy(){return <main className="legal"><nav className="legal-nav"><Link href="/airstream"><ArrowLeft/> AirStream Studio</Link><span>Última actualización / 28 agosto 2026</span></nav><header className="legal-head"><p className="mono">DOCUMENTO / PRIVACIDAD</p><div><h1>Política de privacidad de AirStream Studio</h1><p>Esta política describe cómo AirStream Studio accede a chats públicos, procesa voz localmente y se comunica con OBS.</p></div></header><article className="legal-body">
  <section><span>01</span><div><h2>Resumen</h2><p>AirStream Studio no vende información personal ni opera un servicio de perfiles de usuario. La aplicación reúne datos necesarios para mostrar transmisiones y chats que eliges conectar. Las funciones indicadas como locales, incluidos TTS y subtítulos, se ejecutan en tu dispositivo.</p></div></section>
  <section><span>02</span><div><h2>Chats y plataformas conectadas</h2><p>Al indicar un canal o identificador, la aplicación se comunica directamente con plataformas compatibles, como Twitch y Kick, para mostrar mensajes, nombres públicos, distintivos y eventos relacionados con ese chat. Estos servicios aplican sus propias políticas y pueden recibir información técnica estándar de la conexión.</p></div></section>
  <section><span>03</span><div><h2>Voz, micrófono y subtítulos</h2><p>Si habilitas subtítulos, AirStream Studio accede al micrófono para reconocer la voz y generar texto. El audio usado por esta función se procesa localmente y no se envía a servidores del desarrollador. Los modelos de voz o reconocimiento opcionales pueden descargarse desde sus proveedores antes de utilizarse localmente.</p></div></section>
  <section><span>04</span><div><h2>TTS, filtros y preferencias</h2><p>Los mensajes visibles pueden convertirse en voz en el dispositivo. Filtros, canales, apariencia, atajos y otras preferencias pueden guardarse localmente para restaurar la configuración. La aplicación puede conservar temporalmente mensajes necesarios para mostrarlos, filtrarlos o reproducirlos durante la sesión.</p></div></section>
  <section><span>05</span><div><h2>OBS y red local</h2><p>Si habilitas la integración, AirStream Studio puede conectarse a OBS mediante WebSocket y abrir un servidor local para la superposición. La configuración, contraseña y tráfico de esta función se usan para la conexión que solicitas. No debes exponer el servidor local o las credenciales de OBS a redes no confiables.</p></div></section>
  <section><span>06</span><div><h2>Cambios y contacto</h2><p>Esta política puede actualizarse cuando cambien las plataformas o funciones compatibles. Para solicitar ayuda o hacer preguntas sobre privacidad, escribe a <a href="mailto:dpahuas@gmail.com">dpahuas@gmail.com</a>.</p></div></section>
</article></main>}
